// Type definitions for dashly 1.0.0

// ============ Array ============
export function chunk<T>(array: T[], size?: number): T[][];
export function compact<T>(array: T[]): Exclude<T, null | undefined | false | 0 | ''>[];
export function concat<T>(array: T[], ...values: (T | T[])[]): T[];
export function difference<T>(array: T[], ...excludeArrays: T[][]): T[];
export function differenceBy<T>(array: T[], values: T[], iteratee: ((value: T) => unknown) | string): T[];
export function drop<T>(array: T[], n?: number): T[];
export function dropRight<T>(array: T[], n?: number): T[];
export function dropWhile<T>(array: T[], predicate: (value: T, index: number, array: T[]) => boolean): T[];
export function fill<T>(array: T[], value: T, start?: number, end?: number): T[];
export function flatten<T>(array: (T | T[])[]): T[];
export function flattenDeep<T>(array: any[]): T[];
export function flattenDepth(array: any[], depth?: number): any[];
export function fromPairs<T>(pairs: [string, T][]): Record<string, T>;
export function head<T>(array: T[]): T | undefined;
export function first<T>(array: T[]): T | undefined;
export function last<T>(array: T[]): T | undefined;
export function nth<T>(array: T[], n?: number): T | undefined;
export function initial<T>(array: T[]): T[];
export function tail<T>(array: T[]): T[];
export function intersection<T>(...arrays: T[][]): T[];
export function uniq<T>(array: T[]): T[];
export function uniqBy<T>(array: T[], iteratee: ((value: T) => unknown) | string): T[];
export function union<T>(...arrays: T[][]): T[];
export function without<T>(array: T[], ...values: T[]): T[];
export function zip<T>(...arrays: T[][]): T[][];
export function unzip<T>(array: T[][]): T[][];
export function zipObject<T>(keys: string[], values: T[]): Record<string, T>;
export function take<T>(array: T[], n?: number): T[];
export function takeRight<T>(array: T[], n?: number): T[];
export function takeWhile<T>(array: T[], predicate: (value: T) => boolean): T[];
export function xor<T>(...arrays: T[][]): T[];
export function indexOf<T>(array: T[], value: T, fromIndex?: number): number;
export function reverse<T>(array: T[]): T[];
export function sortedUniq<T>(array: T[]): T[];
export function pull<T>(array: T[], ...values: T[]): T[];
export function remove<T>(array: T[], predicate: (value: T, index: number, array: T[]) => boolean): T[];

// ============ Object ============
export function get(object: any, path: string | (string | number)[], defaultValue?: any): any;
export function set(object: any, path: string | (string | number)[], value: any): any;
export function has(object: any, path: string | (string | number)[]): boolean;
export function hasIn(object: any, path: string | (string | number)[]): boolean;
export function keys(object: any): string[];
export function keysIn(object: any): string[];
export function values<T>(object: Record<string, T>): T[];
export function entries<T>(object: Record<string, T>): [string, T][];
export function toPairs<T>(object: Record<string, T>): [string, T][];
export function assign<T extends object>(object: T, ...sources: any[]): T;
export function assignIn<T extends object>(object: T, ...sources: any[]): T;
export function extend<T extends object>(object: T, ...sources: any[]): T;
export function defaults<T extends object>(object: T, ...sources: any[]): T;
export function merge<T extends object>(object: T, ...sources: any[]): T;
export function pick<T extends object, K extends keyof T>(object: T, paths: K[]): Pick<T, K>;
export function pickBy<T>(object: Record<string, T>, predicate: (value: T, key: string) => boolean): Record<string, T>;
export function omit<T extends object, K extends keyof T>(object: T, paths: K[]): Omit<T, K>;
export function omitBy<T>(object: Record<string, T>, predicate: (value: T, key: string) => boolean): Record<string, T>;
export function forOwn<T>(object: Record<string, T>, iteratee: (value: T, key: string, object: Record<string, T>) => boolean | void): Record<string, T>;
export function invert(object: Record<string, any>): Record<string, string>;
export function invertBy(object: Record<string, any>, iteratee?: (value: any) => string): Record<string, string[]>;
export function mapKeys<T>(object: Record<string, T>, iteratee: (value: T, key: string, object: Record<string, T>) => string): Record<string, T>;
export function mapValues<T, R>(object: Record<string, T>, iteratee: ((value: T, key: string, object: Record<string, T>) => R) | string): Record<string, R>;
export function unset(object: any, path: string | (string | number)[]): boolean;
export function cloneDeep<T>(value: T): T;
export function clone<T>(value: T): T;
export function findKey<T>(object: Record<string, T>, predicate: (value: T, key: string, object: Record<string, T>) => boolean): string | undefined;
export function findLastKey<T>(object: Record<string, T>, predicate: (value: T, key: string, object: Record<string, T>) => boolean): string | undefined;

// ============ String ============
export function words(string: string, pattern?: RegExp | string): string[];
export function camelCase(string: string): string;
export function kebabCase(string: string): string;
export function snakeCase(string: string): string;
export function startCase(string: string): string;
export function capitalize(string: string): string;
export function upperFirst(string: string): string;
export function lowerFirst(string: string): string;
export function toLower(string: string): string;
export function toUpper(string: string): string;
export function lowerCase(string: string): string;
export function upperCase(string: string): string;
export function deburr(string: string): string;
export function truncate(string: string, options?: { length?: number; omission?: string; separator?: RegExp | string }): string;
export function pad(string: string, length?: number, chars?: string): string;
export function padStart(string: string, length?: number, chars?: string): string;
export function padEnd(string: string, length?: number, chars?: string): string;
export function repeat(string: string, n?: number): string;
export function replace(string: string, pattern: RegExp | string, replacement: string | Function): string;
export function split(string: string, separator: RegExp | string, limit?: number): string[];
export function trim(string: string, chars?: string): string;
export function trimStart(string: string, chars?: string): string;
export function trimEnd(string: string, chars?: string): string;
export function startsWith(string: string, target: string, position?: number): boolean;
export function endsWith(string: string, target: string, position?: number): boolean;
export function escape(string: string): string;
export function unescape(string: string): string;
export function escapeRegExp(string: string): string;

// ============ Function ============
export interface DebouncedFunc<T extends (...args: any[]) => any> {
  (...args: Parameters<T>): ReturnType<T>;
  cancel(): void;
  flush(): ReturnType<T>;
  pending(): boolean;
}
export function debounce<T extends (...args: any[]) => any>(func: T, wait?: number, options?: { leading?: boolean; trailing?: boolean; maxWait?: number }): DebouncedFunc<T>;
export function throttle<T extends (...args: any[]) => any>(func: T, wait?: number, options?: { leading?: boolean; trailing?: boolean }): DebouncedFunc<T>;
export interface MemoizedFunction<T extends (...args: any[]) => any> {
  (...args: Parameters<T>): ReturnType<T>;
  cache: Map<any, ReturnType<T>>;
}
export function memoize<T extends (...args: any[]) => any>(func: T, options?: { resolver?: (...args: Parameters<T>) => any; maxSize?: number } | ((...args: Parameters<T>) => any)): MemoizedFunction<T>;
export function once<T extends (...args: any[]) => any>(func: T): T;
export function before<T extends (...args: any[]) => any>(n: number, func: T): T;
export function after<T extends (...args: any[]) => any>(n: number, func: T): T;
export function negate<T extends (...args: any[]) => boolean>(predicate: T): (...args: Parameters<T>) => boolean;
export function unary<T extends (...args: any[]) => any>(func: T): (arg: Parameters<T>[0]) => ReturnType<T>;
export function ary<T extends (...args: any[]) => any>(func: T, n?: number): (...args: any[]) => ReturnType<T>;
export function bind<T extends (...args: any[]) => any>(func: T, thisArg: any, ...partials: any[]): (...args: any[]) => ReturnType<T>;
export function partial<T extends (...args: any[]) => any>(func: T, ...partials: any[]): (...args: any[]) => ReturnType<T>;
export function flip<T extends (...args: any[]) => any>(func: T): T;
export function curry(func: Function, arity?: number): Function;
export function flow(...funcs: (Function | Function[])[]): Function;
export function flowRight(...funcs: (Function | Function[])[]): Function;
export function defer(func: Function, ...args: any[]): number;
export function delay(func: Function, wait: number, ...args: any[]): number;

// ============ Lang ============
export function isArray(value: any): value is any[];
export function isArrayLike(value: any): boolean;
export function isBoolean(value: any): value is boolean;
export function isDate(value: any): value is Date;
export function isEmpty(value: any): boolean;
export function isEqual(value: any, other: any): boolean;
export function isError(value: any): value is Error;
export function isFinite(value: any): boolean;
export function isFunction(value: any): value is Function;
export function isInteger(value: any): boolean;
export function isMap(value: any): value is Map<any, any>;
export function isNaN(value: any): boolean;
export function isNil(value: any): value is null | undefined;
export function isNull(value: any): value is null;
export function isNumber(value: any): value is number;
export function isObject(value: any): boolean;
export function isObjectLike(value: any): boolean;
export function isPlainObject(value: any): boolean;
export function isRegExp(value: any): value is RegExp;
export function isSafeInteger(value: any): boolean;
export function isSet(value: any): value is Set<any>;
export function isString(value: any): value is string;
export function isSymbol(value: any): value is symbol;
export function isUndefined(value: any): value is undefined;
export function isWeakMap(value: any): value is WeakMap<any, any>;
export function isWeakSet(value: any): value is WeakSet<any>;
export function isTypedArray(value: any): boolean;
export function isArguments(value: any): boolean;
export function isArrayBuffer(value: any): value is ArrayBuffer;
export function isBuffer(value: any): boolean;
export function isElement(value: any): boolean;
export function toNumber(value: any): number;
export function toFinite(value: any): number;
export function toInteger(value: any): number;
export function toString(value: any): string;
export function toArray(value: any): any[];
export function eq(value: any, other: any): boolean;
export function gt(value: any, other: any): boolean;
export function gte(value: any, other: any): boolean;
export function lt(value: any, other: any): boolean;
export function lte(value: any, other: any): boolean;
export function castArray<T>(...args: T[]): T[];

// ============ Collection ============
export function forEach<T>(collection: T[] | Record<string, T>, iteratee: (value: T, key: any, collection: any) => boolean | void): typeof collection;
export function each<T>(collection: T[] | Record<string, T>, iteratee: (value: T, key: any, collection: any) => boolean | void): typeof collection;
export function forEachRight<T>(collection: T[] | Record<string, T>, iteratee: (value: T, key: any, collection: any) => boolean | void): typeof collection;
export function eachRight<T>(collection: T[] | Record<string, T>, iteratee: (value: T, key: any, collection: any) => boolean | void): typeof collection;
export function map<T, R>(collection: T[] | Record<string, T>, iteratee: ((value: T, index: number, collection: any) => R) | string): R[];
export function filter<T>(collection: T[] | Record<string, T>, predicate: ((value: T, index: number, collection: any) => boolean) | Partial<T> | string): T[];
export function reject<T>(collection: T[] | Record<string, T>, predicate: ((value: T, index: number, collection: any) => boolean) | Partial<T> | string): T[];
export function find<T>(collection: T[] | Record<string, T>, predicate: ((value: T, index: number, collection: any) => boolean) | Partial<T> | string, fromIndex?: number): T | undefined;
export function findLast<T>(collection: T[] | Record<string, T>, predicate: ((value: T, index: number, collection: any) => boolean) | Partial<T> | string, fromIndex?: number): T | undefined;
export function every<T>(collection: T[] | Record<string, T>, predicate: ((value: T, index: number, collection: any) => boolean) | Partial<T> | string): boolean;
export function some<T>(collection: T[] | Record<string, T>, predicate: ((value: T, index: number, collection: any) => boolean) | Partial<T> | string): boolean;
export function includes<T>(collection: T[] | Record<string, T> | string, value: any, fromIndex?: number): boolean;
export function groupBy<T>(collection: T[] | Record<string, T>, iteratee: ((value: T) => string | number) | string): Record<string, T[]>;
export function keyBy<T>(collection: T[] | Record<string, T>, iteratee: ((value: T) => string | number) | string): Record<string, T>;
export function countBy<T>(collection: T[] | Record<string, T>, iteratee: ((value: T) => string | number) | string): Record<string, number>;
export function reduce<T, R>(collection: T[] | Record<string, T>, iteratee: (accumulator: R, value: T, index: number, collection: any) => R, accumulator?: R): R;
export function reduceRight<T, R>(collection: T[] | Record<string, T>, iteratee: (accumulator: R, value: T, index: number, collection: any) => R, accumulator?: R): R;
export function sortBy<T>(collection: T[] | Record<string, T>, iteratees: ((value: T) => any) | string | Array<((value: T) => any) | string>): T[];
export function orderBy<T>(collection: T[] | Record<string, T>, iteratees: Array<((value: T) => any) | string>, orders?: ('asc' | 'desc')[]): T[];
export function flatMap<T, R>(collection: T[] | Record<string, T>, iteratee: (value: T, index: number, collection: any) => R | R[]): R[];
export function flatMapDeep<T, R>(collection: T[] | Record<string, T>, iteratee: (value: T, index: number, collection: any) => any): R[];
export function partition<T>(collection: T[] | Record<string, T>, predicate: ((value: T) => boolean) | Partial<T> | string): [T[], T[]];
export function sample<T>(collection: T[] | Record<string, T>): T | undefined;
export function sampleSize<T>(collection: T[] | Record<string, T>, n?: number): T[];
export function shuffle<T>(collection: T[] | Record<string, T>): T[];
export function size(collection: any): number;
export function invokeMap<T>(collection: T[] | Record<string, T>, methodName: string | Function, ...args: any[]): any[];

// ============ Math ============
export function add(augend: number, addend: number): number;
export function subtract(minuend: number, subtrahend: number): number;
export function multiply(multiplier: number, multiplicand: number): number;
export function divide(dividend: number, divisor: number): number;
export function ceil(number: number, precision?: number): number;
export function floor(number: number, precision?: number): number;
export function round(number: number, precision?: number): number;
export function max(array: number[]): number | undefined;
export function maxBy<T>(array: T[], iteratee: ((value: T) => number) | string): T | undefined;
export function min(array: number[]): number | undefined;
export function minBy<T>(array: T[], iteratee: ((value: T) => number) | string): T | undefined;
export function sum(array: number[]): number;
export function sumBy<T>(array: T[], iteratee: ((value: T) => number) | string): number;
export function mean(array: number[]): number;
export function meanBy<T>(array: T[], iteratee: ((value: T) => number) | string): number;
export function clamp(number: number, lower: number, upper: number): number;
export function inRange(number: number, start: number, end?: number): boolean;
export function random(lower?: number, upper?: number, floating?: boolean): number;

// ============ Util ============
export function identity<T>(value: T): T;
export function constant<T>(value: T): () => T;
export function noop(): void;
export function times<T>(n: number, iteratee?: (index: number) => T): T[];
export function uniqueId(prefix?: string): string;
export function defaultTo<T>(value: T | null | undefined, defaultValue: T): T;
export function range(start?: number, end?: number, step?: number): number[];
export function rangeRight(start?: number, end?: number, step?: number): number[];
export function stubArray(): any[];
export function stubObject(): object;
export function stubString(): string;
export function stubTrue(): true;
export function stubFalse(): false;
export function attempt<T>(func: (...args: any[]) => T, ...args: any[]): T | Error;
export function matches<T>(source: Partial<T>): (object: T) => boolean;
export function matchesProperty(path: string | string[], srcValue: any): (object: any) => boolean;
export function property(path: string | string[]): (object: any) => any;
export function propertyOf(object: any): (path: string | string[]) => any;
export function toPath(value: string | string[]): string[];
export function conformsTo(object: any, source: Record<string, (value: any) => boolean>): boolean;
export function over(...iteratees: (Function | Function[])[]): (...args: any[]) => any[];
export function overEvery(...predicates: (Function | Function[])[]): (...args: any[]) => boolean;
export function overSome(...predicates: (Function | Function[])[]): (...args: any[]) => boolean;
